# values in this file are for test purposes

endpoint:
  ip: 192.168.2.230
  user: ivonet

disk:
  uuid: 647ef8a7-583c-4c15-882b-78bbaec144cd
  mountpoint: /media/backup

watch:
  description: Start watching the for backup disk to mount...
  command: ls /dev/disk/by-uid
  action:
    description:
      yes: Mounting backup disk
      no: Other uuid found so doing nothing...